package br.com.github.macgarcia.main;

import br.com.github.macgarcia.service.TelaInicialService;

/**
 *
 * @author macgarcia
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private final TelaInicialService service;
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        service = new TelaInicialService(this);
        service.configurarAcoesDosBotoesDaBarraDeMenu(jMenuBar, desktop);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemCadastroImagem = new javax.swing.JMenuItem();
        jMenuItemListarImagens = new javax.swing.JMenuItem();
        jMenuItemCapturarImagem = new javax.swing.JMenuItem();
        jMenuProcessamentoImagem = new javax.swing.JMenu();
        jMenuItemComparacaoImagem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuArquivo.setText("Arquivo");

        jMenuItemCadastroImagem.setText("Cadastro de imagem");
        jMenuArquivo.add(jMenuItemCadastroImagem);

        jMenuItemListarImagens.setText("Listar Imagens");
        jMenuArquivo.add(jMenuItemListarImagens);

        jMenuItemCapturarImagem.setText("Capturar imagem");
        jMenuArquivo.add(jMenuItemCapturarImagem);

        jMenuBar.add(jMenuArquivo);

        jMenuProcessamentoImagem.setText("Processamento de imagem");

        jMenuItemComparacaoImagem.setText("Comparação por histograma");
        jMenuProcessamentoImagem.add(jMenuItemComparacaoImagem);

        jMenuBar.add(jMenuProcessamentoImagem);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCadastroImagem;
    private javax.swing.JMenuItem jMenuItemCapturarImagem;
    private javax.swing.JMenuItem jMenuItemComparacaoImagem;
    private javax.swing.JMenuItem jMenuItemListarImagens;
    private javax.swing.JMenu jMenuProcessamentoImagem;
    // End of variables declaration//GEN-END:variables
}
