package br.com.github.macgarcia.view;

import br.com.github.macgarcia.service.TelaEdicaoImagemService;
import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author macgarcia
 */
public class TelaEdicaoImagem extends javax.swing.JInternalFrame {
    
    private final TelaEdicaoImagemService service;

    /**
     * Creates new form TelaEdicaoImagem
     */
    public TelaEdicaoImagem() {
        initComponents();
        service = new TelaEdicaoImagemService(this);
        List<JButton> botoes = Arrays.asList(btnProcurar, btnTonsDeCinza, btnPassaAlta, btnBlur);
        service.acaoDosBotoes(botoes, lblImagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProcurar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTonsDeCinza = new javax.swing.JButton();
        btnPassaAlta = new javax.swing.JButton();
        btnBlur = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Selecionar imagem");

        btnProcurar.setText("Procurar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Imagem selecionada");

        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Filtros");

        btnTonsDeCinza.setText("Tons de cinza");

        btnPassaAlta.setText("Passa alta");

        btnBlur.setText("Blur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(btnProcurar))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTonsDeCinza)
                                .addGap(18, 18, 18)
                                .addComponent(btnPassaAlta)
                                .addGap(18, 18, 18)
                                .addComponent(btnBlur)))
                        .addGap(0, 770, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcurar)
                    .addComponent(btnTonsDeCinza)
                    .addComponent(btnPassaAlta)
                    .addComponent(btnBlur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlur;
    private javax.swing.JButton btnPassaAlta;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnTonsDeCinza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables
}
