package br.com.github.macgarcia.view;

import br.com.github.macgarcia.service.TelaEdicaoImagemService;
import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author macgarcia
 */
public class TelaEdicaoImagem extends javax.swing.JInternalFrame {

    private final TelaEdicaoImagemService service;

    /**
     * Creates new form TelaEdicaoImagem
     */
    public TelaEdicaoImagem() {
        initComponents();
        service = new TelaEdicaoImagemService(this);
        List<JButton> botoes = Arrays.asList(btnProcurar, btnOriginal, btnTonsDeCinza, 
                btnPassaAlta, btnBlur, btnSuavizar, btnErosao, btnSaturacao, btnSobel);
        service.acaoDosBotoes(botoes, lblImagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProcurar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTonsDeCinza = new javax.swing.JButton();
        btnPassaAlta = new javax.swing.JButton();
        btnBlur = new javax.swing.JButton();
        btnSuavizar = new javax.swing.JButton();
        btnErosao = new javax.swing.JButton();
        btnSaturacao = new javax.swing.JButton();
        btnOriginal = new javax.swing.JButton();
        btnSobel = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Selecionar imagem");

        btnProcurar.setText("Procurar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Imagem selecionada");

        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Filtros");

        btnTonsDeCinza.setText("Tons de cinza");

        btnPassaAlta.setText("Passa alta");

        btnBlur.setText("Blur");

        btnSuavizar.setText("Suavizar");

        btnErosao.setText("Erosão");

        btnSaturacao.setText("Saturação");

        btnOriginal.setText("Original");

        btnSobel.setText("Sobel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 1242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(121, 121, 121)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcurar)
                        .addGap(153, 153, 153)
                        .addComponent(btnOriginal)
                        .addGap(18, 18, 18)
                        .addComponent(btnTonsDeCinza)
                        .addGap(18, 18, 18)
                        .addComponent(btnPassaAlta)
                        .addGap(18, 18, 18)
                        .addComponent(btnBlur)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuavizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnErosao)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaturacao)
                        .addGap(18, 18, 18)
                        .addComponent(btnSobel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcurar)
                    .addComponent(btnTonsDeCinza)
                    .addComponent(btnPassaAlta)
                    .addComponent(btnBlur)
                    .addComponent(btnSuavizar)
                    .addComponent(btnErosao)
                    .addComponent(btnSaturacao)
                    .addComponent(btnOriginal)
                    .addComponent(btnSobel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlur;
    private javax.swing.JButton btnErosao;
    private javax.swing.JButton btnOriginal;
    private javax.swing.JButton btnPassaAlta;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnSaturacao;
    private javax.swing.JButton btnSobel;
    private javax.swing.JButton btnSuavizar;
    private javax.swing.JButton btnTonsDeCinza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables
}
